version: '3'
services:
  # Node.js app service
  app:
    build: .
    container_name: node-app
    ports:
      - "${PORT:-3000}:3600"  # Map host port to container port
    volumes:
      - .:/app  # Sync project files with container
      - /app/node_modules  # Prevent overriding node_modules
    environment:
      - MONGO_URI=${MONGO_URI}  # Fetch MongoDB URI from environment
      - PORT=${PORT}            # Pass the port variable to the app
    command: npm run server  # Command to run the Node.js app